// Application and Group CRUD
export const ADD_APPLICATION = "ADD_APPLICATION";
export const ADD_APPLICATION_GROUP = "ADD_APPLICATION_GROUP";

export const GET_APPLICATION = "GET_APPLICATION";
export const GET_APPLICATION_GROUP = "GET_APPLICATION_GROUP";

export const UPDATE_APPLICATION = "UPDATE_APPLICATION";
export const UPDATE_APPLICATION_GROUP = "UPDATE_APPLICATION_GROUP";

export const DELETE_APPLICATION = "DELETE_APPLICATION";
export const DELETE_APPLICATION_GROUP = "DELETE_APPLICATION_GROUP";

// Application other API actions
export const LOAD_APPLICATIONS = "LOAD_APPLICATIONS";
export const LOAD_APPLICATION_GROUPS = "LOAD_APPLICATION_GROUPS";
export const LOAD_APPLICATIONS_AND_GROUPS = "LOAD_APPLICATIONS_AND_GROUPS";

export const COPY_APPLICATION = "COPY_APPLICATION";
export const COPY_APPLICATION_GROUP = "COPY_APPLICATION_GROUP";

// Some operations
export const CLOSE_APPLICATION_EDITOR = "CLOSE_APPLICATION_EDITOR";
export const CLOSE_APPLICATION_WIZARD = "CLOSE_APPLICATION_WIZARD";
export const CLOSE_SUB_APP_EDITOR = "CLOSE_SUB_APP_EDITOR";

export const OPEN_APPLICATION_EDITOR = "OPEN_APPLICATION_EDITOR";
export const OPEN_APPLICATION_WIZARD = "OPEN_APPLICATION_WIZARD";
export const OPEN_SUB_APP_EDITOR = "OPEN_SUB_APP_EDITOR";

// Status change
export const WS_NOTIFICATION_APPLICATION_STATUS =
  "WS_NOTIFICATION_APPLICATION_STATUS";

// update app list
export const UPDATE_APP_LIST = "UPDATE_APP_LIST";

// update app group list
export const UPDATE_APP_GROUP_LIST = "UPDATE_APP_GROUP_LIST";
