// Package actions.
export const COPY_PACKAGE = "COPY_PACKAGE";
export const DELETE_PACKAGE = "DELETE_PACKAGE";
export const DOWNLOAD_PACKAGE = "DOWNLOAD_PACKAGE";
export const LOAD_PACKAGES = "LOAD_PACKAGES";
export const LOCK_PACKAGE = "LOCK_PACKAGE";
export const RENAME_PACKAGE = "RENAME_PACKAGE";
export const UPLOAD_PACKAGE = "UPLOAD_PACKAGE";

// Firmware package settings
export const LOAD_FIRMWARE_SETTINGS = "LOAD_FIRMWARE_SETTINGS";
export const UPDATE_FIRMWARE_SETTING = "UPDATE_FIRMWARE_SETTING";

// License
export const LOAD_LICENSES = "LOAD_LICENSES";
export const REQUEST_LICENSE = "REQUEST_LICENSE";
export const CLEAR_INSTALLED_ID = "CLEAR_INSTALLED_ID";
