// Terminal and Group CRUD
export const ADD_TERMINAL = "ADD_TERMINAL";
export const ADD_TERMINAL_GROUP = "ADD_TERMINAL_GROUP";

export const GET_TERMINAL = "GET_TERMINAL";
export const GET_TERMINAL_GROUP = "GET_TERMINAL_GROUP";

export const UPDATE_TERMINAL = "UPDATE_TERMINAL";
export const UPDATE_TERMINAL_GROUP = "UPDATE_TERMINAL_GROUP";

export const DELETE_TERMINAL = "DELETE_TERMINAL";
export const DELETE_TERMINAL_GROUP = "DELETE_TERMINAL_GROUP";

// Terminal other API actions
export const LOAD_TERMINALS = "LOAD_TERMINALS";
export const LOAD_TERMINAL_GROUPS = "LOAD_TERMINAL_GROUPS";
export const LOAD_TERMINALS_AND_GROUPS = "LOAD_TERMINALS_AND_GROUPS";

export const COPY_TERMINAL = "COPY_TERMINAL";
export const COPY_TERMINAL_GROUP = "COPY_TERMINAL_GROUP";

export const GET_PARENT_TERMINAL_GROUP = "GET_PARENT_TERMINAL_GROUP";
export const CLEAR_PARENT_TERMINAL_GROUP = "CLEAR_PARENT_TERMINAL_GROUP";

// Some operations
export const CLOSE_TERMINAL_EDITOR = "CLOSE_TERMINAL_EDITOR";
export const CLOSE_TERMINAL_WIZARD = "CLOSE_TERMINAL_WIZARD";

export const OPEN_TERMINAL_EDITOR = "OPEN_TERMINAL_EDITOR";
export const OPEN_TERMINAL_WIZARD = "OPEN_TERMINAL_WIZARD";

// Modules
export const LOAD_MODULES = "LOAD_MODULES";
export const LOAD_MODULE_SETTING = "LOAD_MODULE_SETTING";

// Others
export const CLEAR_AUTH_VERIFY = "CLEAR_AUTH_VERIFY";
export const CLEAR_TERMINAL_SETTING = "CLEAR_TERMINAL_SETTING";
export const GET_DEFAULT_MOUSE_MAPPING = "GET_DEFAULT_MOUSE_MAPPING";
export const GET_DEFAULT_KEYBOARD_MAPPING = "GET_DEFAULT_KEYBOARD_MAPPING";
export const GET_FIRMWARE_PACKAGE = "GET_FIRMWARE_PACKAGE";
export const GET_DISPLAY_OPTIONS = "GET_DISPLAY_OPTIONS";
export const GET_MODEL_MAP = "GET_MODEL_MAP";
export const GET_TERMINAL_SETTING = "GET_TERMINAL_SETTING";
export const OPERATE_TERMINAL = "OPERATE_TERMINAL";

// new hardware type
export const MODEL = "MODEL";

// Status change
export const WS_NOTIFICATION_TERMINAL = "WS_NOTIFICATION_TERMINAL";
export const WS_NOTIFICATION_TERMINAL_LIST= "WS_NOTIFICATION_TERMINAL_LIST";
export const WS_NOTIFICATION_TERMINAL_STATUS = "WS_NOTIFICATION_TERMINAL_STATUS";

// update terminal list
export const UPDATE_TERMINAL_LIST = "UPDATE_TERMINAL_LIST";

// update terminal group list
export const UPDATE_TERMINAL_GROUP_LIST = "UPDATE_TERMINAL_GROUP_LIST";

// Pending terminal
export const WS_NOTIFICATION_PENDING_TERMINALS =
  "WS_NOTIFICATION_PENDING_TERMINALS";
export const INITIAL_PENDING_TERMINALS = "INITIAL_PENDING_TERMINALS";
