export const DefaultOverride = {
  DisplayName: "",
  Username: "",
  Password: "",
  Domain: "",
  LinkedAppCommandOptions: "",
  Resolution: "1920 x 1080",
  SessionWidth: 1920,
  SessionHeight: 1080,
  ColorDepth: "16M",
  DisplayNameOverride: false,
  UserAccessOverride: false,
  AppCommandOverride: false,
  VideoSettingOverride: false,
};

export const DefaultAppOverride = {
  Name: "",
  Favorite: false,
  ModifiedTS: 0,
  Id: 0,
  ParentId: 0,
  AppId: 0,
  Tid: 0,
  DisplayName: "",
  Username: "",
  Password: "",
  Domain: "",
  LinkedAppCommandOptions: "",
  Resolution: "1920 x 1080",
  SessionHeight: 1080,
  SessionWidth: 1920,
  ColorDepth: "16M",
  DisplayNameOverride: false,
  UserAccessOverride: false,
  AppCommandOverride: false,
  VideoSettingOverride: false,
};
